### ISSUE TITLE
adding an aws route table entry is not reported

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#362]
**Description**

Slight inconsistency in AWS VPC Route Tables drift detection!

Using the TF resources `aws_route_table` and linking a route using `aws_route`, I then manually add a second route using the AWS console. 

Issue 1: There I expect driftctl to detect the drift, and it doesn't.
Issue 2: Then if I terraform apply again, the new route is integrated into the terraform state ... but then driftctl shows both routes as deleted.

In the state, after the apply, both routes (TF and manual) are included in an `aws_route_table` resource, while the "old" `aws_route` entry is still there. 

**Environment**
 - OS: fedora 33
 - driftctl version: 0.7.0

**How to reproduce**

Here's a minimal TF config

 I think is enough to reproduce: 

```hcl

resource "aws_default_vpc" "default" {
  tags = {
    Name = "Default VPC"
  }
}

resource "aws_internet_gateway" "staging_gw" {
  vpc_id = aws_default_vpc.default.id

  tags = {
    Name      = "Staging Internet Gateway"
    Terraform = "true"
  }
}

resource "aws_route_table" "table" {
  vpc_id = aws_default_vpc.default.id

  tags = {
    Name      = "Another Route Table"
    Terraform = "true"
  }
}

resource "aws_route" "route_1" {
  route_table_id         = aws_route_table.table.id
  destination_cidr_block = "10.0.1.0/24"
  gateway_id = aws_internet_gateway.staging_gw.id
}
```

1. apply this
2. add a second route in the table (10.0.2.0/24 or whatever)
3. driftctl scan: no drift detected (expected to be detected) 
4. terraform apply: driftctl detects both routes as "deleted"

```
Found deleted resources:
  aws_route:
    - Table: rtb-0cbbbdf6badb3140c, Destination: 10.0.2.0/24
    - Table: rtb-0cbbbdf6badb3140c, Destination: 10.0.1.0/24
Found 8 resource(s)
 - 75% coverage
 - 6 covered by IaC
 - 0 not covered by IaC
 - 2 deleted on cloud provider
 - 0/6 drifted from IaC
```

Also linked is the final terraform state. 
[terraform.tfstate.gz](https://github.com/cloudskiff/driftctl/files/6191221/terraform.tfstate.gz)

**Possible Solution**

**Additional context**
